---
- name: Test AWS connection
  hosts: awsinstances
  remote_user: ec2-user

  tasks:
    - name: Create Directory
      command: touch test.txt

    - name: Echo command
      shell: echo "Connected to AWS instance" > test.txt 
    - name: Install Docker
      shell: sudo yum update -y && sudo yum install docker -y

    - name: Start Docker
      shell: sudo service docker start

    - name: Add ec2-user to docker group
      shell: sudo usermod -a -G docker ec2-user

    - name: Install Kubectl
      shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install Conntrack
      shell: sudo yum install -y conntrack

    - name: Install Minikube
      shell: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64

    - name: Copy K8s files
      copy: src=../k8s-specifications dest=/home/ec2-user/voting-app

    - name: Start Minikube
      shell: minikube start --driver=docker

    - name: Deploy K8s files
      shell: kubectl apply -f /home/ec2-user/voting-app/k8s-specifications
